import { useEffect, useState } from "react";
import type { ChangeEvent } from "react";
import type { UserProfile } from "@cup/shared-types";
import { useAuth } from "../../auth";
import { fetchMyProfile, updateMyProfile } from "../../api/user";

type FormState = {
  username: string;
  email: string;
  displayName: string;
};

type ProfileField = "avatar" | "username" | "displayName" | "email";

function createFieldStateMap<T>(value: T): Record<ProfileField, T> {
  return {
    avatar: value,
    username: value,
    displayName: value,
    email: value,
  };
}

const DEFAULT_AVATAR_SRC = "/images/avatars/default-profile.png";

export default function ProfilePage() {
  const { user, isLoading, refresh } = useAuth();
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [form, setForm] = useState<FormState>({ username: "", email: "", displayName: "" });
  const [selectedAvatarFile, setSelectedAvatarFile] = useState<File | null>(null);
  const [avatarPreviewSrc, setAvatarPreviewSrc] = useState<string>(DEFAULT_AVATAR_SRC);

  const [isHydrating, setIsHydrating] = useState(false);
  const [loadErrorMessage, setLoadErrorMessage] = useState<string | null>(null);

  const [editingByField, setEditingByField] = useState<Record<ProfileField, boolean>>(createFieldStateMap(false));
  const [savingByField, setSavingByField] = useState<Record<ProfileField, boolean>>(createFieldStateMap(false));
  const [errorByField, setErrorByField] = useState<Record<ProfileField, string | null>>(createFieldStateMap(null));

  useEffect(() => { //deps: [user?.id]. Hydrates profile fields
    if (!user?.id) {
      return;
    }

    let active = true;

    const loadProfile = async () => {
      setIsHydrating(true);
      setLoadErrorMessage(null);

      try {
        const nextProfile = await fetchMyProfile();
        if (!active) {
          return;
        }

        setForm({
          username: nextProfile.username,
          email: nextProfile.email ?? "",
          displayName: nextProfile.displayName ?? "",
        });
        setProfile(nextProfile);
        setEditingByField(createFieldStateMap(false));
        setSavingByField(createFieldStateMap(false));
        setErrorByField(createFieldStateMap(null));
        setSelectedAvatarFile(null);
        setAvatarPreviewSrc(DEFAULT_AVATAR_SRC);
      } catch (error) {
        if (!active) {
          return;
        }
        setLoadErrorMessage(error instanceof Error ? error.message : "Failed to load profile.");
      } finally {
        if (active) {
          setIsHydrating(false);
        }
      }
    };

    void loadProfile();

    return () => {
      active = false;
    };
  }, [user?.id]);

  //when avatarPreviewSrc is changed(e.g. user selects a new image file for avatar), the cleanup function here will clear the blob for the previously selected image.
  useEffect(() => { 
    if (!avatarPreviewSrc.startsWith("blob:")) {
      return;
    }

    return () => {
      URL.revokeObjectURL(avatarPreviewSrc);
    };
  }, [avatarPreviewSrc]);

  //bools that indicate whether a profile value has changed(e.g. used to determine whether or not to show 'save' button for that field)
  const isUsernameDirty = profile ? profile.username !== form.username.trim() : false;
  const isDisplayNameDirty = profile ? (profile.displayName ?? "") !== form.displayName.trim() : false;
  const isEmailDirty = profile ? (profile.email ?? "") !== form.email.trim() : false;
  const isAvatarDirty = selectedAvatarFile !== null;

  const shouldPromptCustomUsername =
    (profile?.usernameAutoGenerated ?? false) || /^newuser\d*$/i.test(form.username.trim());

  const setFieldEditing = (field: ProfileField, value: boolean) => {
    setEditingByField((previous) => ({ ...previous, [field]: value }));
  };

  const setFieldSaving = (field: ProfileField, value: boolean) => {
    setSavingByField((previous) => ({ ...previous, [field]: value }));
  };

  const setFieldError = (field: ProfileField, message: string | null) => {
    setErrorByField((previous) => ({ ...previous, [field]: message }));
  };

  const beginEdit = (field: ProfileField) => {
    setFieldError(field, null);
    setFieldEditing(field, true);
  };

  const cancelEdit = (field: ProfileField) => {
    if (!profile) {
      return;
    }

    if (field === "username") {
      setForm((previous) => ({ ...previous, username: profile.username }));
    }

    if (field === "displayName") {
      setForm((previous) => ({ ...previous, displayName: profile.displayName ?? "" }));
    }

    if (field === "email") {
      setForm((previous) => ({ ...previous, email: profile.email ?? "" }));
    }

    if (field === "avatar") {
      setSelectedAvatarFile(null);
      setAvatarPreviewSrc(DEFAULT_AVATAR_SRC);
    }

    setFieldError(field, null);
    setFieldEditing(field, false);
  };

  const handleAvatarFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0] ?? null;
    setSelectedAvatarFile(file);

    if (!file) {
      setAvatarPreviewSrc(DEFAULT_AVATAR_SRC);
      return;
    }

    const localPreviewUrl = URL.createObjectURL(file);
    setAvatarPreviewSrc(localPreviewUrl);
    event.currentTarget.value = "";
  };

  const handleSaveUsername = async () => {
    if (!profile) {
      return;
    }

    if (!isUsernameDirty) {
      setFieldEditing("username", false);
      return;
    }

    try {
      setFieldSaving("username", true);
      setFieldError("username", null);

      const updated = await updateMyProfile({ username: form.username.trim() });
      setForm((previous) => ({ ...previous, username: updated.username }));
      setProfile(updated);
      setFieldEditing("username", false);
      await refresh();
    } catch (error) {
      setFieldError("username", error instanceof Error ? error.message : "Failed to save username.");
    } finally {
      setFieldSaving("username", false);
    }
  };

  const handleSaveDisplayName = async () => {
    if (!profile) {
      return;
    }

    if (!isDisplayNameDirty) {
      setFieldEditing("displayName", false);
      return;
    }

    try {
      setFieldSaving("displayName", true);
      setFieldError("displayName", null);

      const trimmedDisplayName = form.displayName.trim();
      const updated = await updateMyProfile({ displayName: trimmedDisplayName ? trimmedDisplayName : null });

      setForm((previous) => ({ ...previous, displayName: updated.displayName ?? "" }));
      setProfile(updated);
      setFieldEditing("displayName", false);
      await refresh();
    } catch (error) {
      setFieldError("displayName", error instanceof Error ? error.message : "Failed to save display name.");
    } finally {
      setFieldSaving("displayName", false);
    }
  };

  const handleSaveEmail = async () => {
    if (!profile) {
      return;
    }

    if (!isEmailDirty) {
      setFieldEditing("email", false);
      return;
    }

    try {
      setFieldSaving("email", true);
      setFieldError("email", null);

      const trimmedEmail = form.email.trim();
      const updated = await updateMyProfile({ email: trimmedEmail ? trimmedEmail : null });

      setForm((previous) => ({ ...previous, email: updated.email ?? "" }));
      setProfile(updated);
      setFieldEditing("email", false);
      await refresh();
    } catch (error) {
      setFieldError("email", error instanceof Error ? error.message : "Failed to save email.");
    } finally {
      setFieldSaving("email", false);
    }
  };

  const handleSaveAvatar = async () => {
    if (!isAvatarDirty) {
      setFieldEditing("avatar", false);
      return;
    }

    try {
      setFieldSaving("avatar", true);
      setFieldError("avatar", null);

      // Backend upload wiring is intentionally deferred.
      setSelectedAvatarFile(null);
      setFieldEditing("avatar", false);
    } catch (error) {
      setFieldError("avatar", error instanceof Error ? error.message : "Failed to save profile picture.");
    } finally {
      setFieldSaving("avatar", false);
    }
  };

  if (isLoading) {
    return <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]" />;
  }

  if (user && (isHydrating || !profile)) {
    return <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]" />;
  }

  if (!user) {
    return (
      <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]">
        <div className="mx-auto w-full max-w-3xl rounded-xl border border-[color:var(--line)] bg-[color:var(--panel)]/90 p-5">
          You are not logged in.
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]">
      <div className="mx-auto w-full max-w-3xl rounded-2xl border border-[color:var(--line)] bg-[color:var(--panel)]/90 p-6">
        <h1 className="text-2xl font-semibold tracking-tight">Profile</h1>

        {shouldPromptCustomUsername && (
          <p className="mt-3 rounded-md border border-yellow-500/50 bg-yellow-500/10 px-3 py-2 text-sm text-yellow-300">
            Set a custom user name to personalize your account.
          </p>
        )}

        {!form.displayName.trim() && (
          <p className="mt-3 rounded-md border border-yellow-500/50 bg-yellow-500/10 px-3 py-2 text-sm text-yellow-300">
            Please set a display name soon so friends can recognize you.
          </p>
        )}

        {loadErrorMessage && (
          <p className="mt-3 rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-300">
            {loadErrorMessage}
          </p>
        )}

        <div className="mt-5 grid gap-4">
          <div className="rounded-md border border-[color:var(--line)] bg-[color:var(--panel-strong)] px-4 py-3">
            <div className="flex items-center justify-between gap-3">
              <p className="text-xs uppercase tracking-[0.2em] text-[color:var(--muted)]">Profile picture</p>

              {editingByField.avatar ? (
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => void handleSaveAvatar()}
                    disabled={savingByField.avatar || !isAvatarDirty}
                    className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition enabled:hover:border-[color:var(--text)] disabled:opacity-60"
                  >
                    {savingByField.avatar ? "Saving..." : "Save"}
                  </button>
                  <button
                    type="button"
                    onClick={() => cancelEdit("avatar")}
                    className="text-xs text-[color:var(--muted)] transition hover:text-[color:var(--text)]"
                  >
                    Cancel
                  </button>
                </div>
              ) : (
                <button
                  type="button"
                  onClick={() => beginEdit("avatar")}
                  className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition hover:border-[color:var(--text)]"
                >
                  Edit
                </button>
              )}
            </div>

            <div className="mt-3 flex items-center gap-4">
              <img
                src={avatarPreviewSrc}
                alt="Profile picture preview"
                className="h-20 w-20 rounded-full border border-[color:var(--line)] object-cover bg-[color:var(--panel)]"
                onError={() => setAvatarPreviewSrc(DEFAULT_AVATAR_SRC)}
              />

              <div className="min-w-0 w-full">
                {editingByField.avatar ? (
                  <input
                    type="file"
                    accept="image/png,image/jpeg,image/webp"
                    onChange={handleAvatarFileChange}
                    className="w-full block text-sm text-[color:var(--muted)] file:mr-3 file:rounded-full file:border file:border-[color:var(--line)] file:bg-transparent file:px-3 file:py-1.5 file:text-sm file:text-[color:var(--text)] hover:file:border-[color:var(--text)]"
                  />
                ) : null}

                {editingByField.avatar ? (
                  <p className="mt-1 text-sm text-[color:var(--muted)]">
                    {selectedAvatarFile ? selectedAvatarFile.name : "Choose JPG, PNG, or WEBP"}
                  </p>
                ) : null}
              </div>
            </div>

            {errorByField.avatar ? (
              <p className="mt-2 rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-xs text-red-300">
                {errorByField.avatar}
              </p>
            ) : null}
          </div>

          <div className="rounded-md border border-[color:var(--line)] bg-[color:var(--panel-strong)] px-4 py-3">
            <div className="flex items-center justify-between gap-3">
              <p className="text-xs uppercase tracking-[0.2em] text-[color:var(--muted)]">Username</p>

              {editingByField.username ? (
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => void handleSaveUsername()}
                    disabled={savingByField.username || !isUsernameDirty}
                    className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition enabled:hover:border-[color:var(--text)] disabled:opacity-60"
                  >
                    {savingByField.username ? "Saving..." : "Save"}
                  </button>
                  <button
                    type="button"
                    onClick={() => cancelEdit("username")}
                    className="text-xs text-[color:var(--muted)] transition hover:text-[color:var(--text)]"
                  >
                    Cancel
                  </button>
                </div>
              ) : (
                <button
                  type="button"
                  onClick={() => beginEdit("username")}
                  className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition hover:border-[color:var(--text)]"
                >
                  Edit
                </button>
              )}
            </div>

            {editingByField.username ? (
              <input
                id="profile-username"
                value={form.username}
                onChange={(event) => setForm((previous) => ({ ...previous, username: event.target.value }))}
                className="mt-2 w-full rounded-md border border-[color:var(--line)] bg-[color:var(--panel)] px-3 py-2 text-[color:var(--text)] outline-none focus:border-[color:var(--accent)]"
              />
            ) : (
              <p className="mt-1 text-base font-semibold text-[color:var(--text)]">{form.username}</p>
            )}

            {errorByField.username ? (
              <p className="mt-2 rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-xs text-red-300">
                {errorByField.username}
              </p>
            ) : null}
          </div>

          <div className="rounded-md border border-[color:var(--line)] bg-[color:var(--panel-strong)] px-4 py-3">
            <div className="flex items-center justify-between gap-3">
              <p className="text-xs uppercase tracking-[0.2em] text-[color:var(--muted)]">Display name</p>

              {editingByField.displayName ? (
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => void handleSaveDisplayName()}
                    disabled={savingByField.displayName || !isDisplayNameDirty}
                    className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition enabled:hover:border-[color:var(--text)] disabled:opacity-60"
                  >
                    {savingByField.displayName ? "Saving..." : "Save"}
                  </button>
                  <button
                    type="button"
                    onClick={() => cancelEdit("displayName")}
                    className="text-xs text-[color:var(--muted)] transition hover:text-[color:var(--text)]"
                  >
                    Cancel
                  </button>
                </div>
              ) : (
                <button
                  type="button"
                  onClick={() => beginEdit("displayName")}
                  className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition hover:border-[color:var(--text)]"
                >
                  Edit
                </button>
              )}
            </div>

            {editingByField.displayName ? (
              <input
                id="profile-display-name"
                value={form.displayName}
                onChange={(event) => setForm((previous) => ({ ...previous, displayName: event.target.value }))}
                placeholder="Set your display name"
                className="mt-2 w-full rounded-md border border-[color:var(--line)] bg-[color:var(--panel)] px-3 py-2 text-[color:var(--text)] outline-none focus:border-[color:var(--accent)]"
              />
            ) : (
              <p className="mt-1 text-base font-semibold text-[color:var(--text)]">
                {form.displayName.trim() || "Not set"}
              </p>
            )}

            {errorByField.displayName ? (
              <p className="mt-2 rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-xs text-red-300">
                {errorByField.displayName}
              </p>
            ) : null}
          </div>

          <div className="rounded-md border border-[color:var(--line)] bg-[color:var(--panel-strong)] px-4 py-3">
            <div className="flex items-center justify-between gap-3">
              <p className="text-xs uppercase tracking-[0.2em] text-[color:var(--muted)]">Email (optional)</p>

              {editingByField.email ? (
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => void handleSaveEmail()}
                    disabled={savingByField.email || !isEmailDirty}
                    className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition enabled:hover:border-[color:var(--text)] disabled:opacity-60"
                  >
                    {savingByField.email ? "Saving..." : "Save"}
                  </button>
                  <button
                    type="button"
                    onClick={() => cancelEdit("email")}
                    className="text-xs text-[color:var(--muted)] transition hover:text-[color:var(--text)]"
                  >
                    Cancel
                  </button>
                </div>
              ) : (
                <button
                  type="button"
                  onClick={() => beginEdit("email")}
                  className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition hover:border-[color:var(--text)]"
                >
                  Edit
                </button>
              )}
            </div>

            {editingByField.email ? (
              <input
                id="profile-email"
                type="email"
                value={form.email}
                onChange={(event) => setForm((previous) => ({ ...previous, email: event.target.value }))}
                placeholder="Add an email for recovery"
                className="mt-2 w-full rounded-md border border-[color:var(--line)] bg-[color:var(--panel)] px-3 py-2 text-[color:var(--text)] outline-none focus:border-[color:var(--accent)]"
              />
            ) : (
              <p className="mt-1 text-base font-semibold text-[color:var(--text)]">{form.email.trim() || "Not set"}</p>
            )}

            {errorByField.email ? (
              <p className="mt-2 rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-xs text-red-300">
                {errorByField.email}
              </p>
            ) : null}
          </div>
        </div>
      </div>
    </main>
  );
}
