import { useEffect, useState } from "react";
import type { ChangeEvent } from "react";
import type { UserProfile } from "@cup/shared-types";
import { useAuth } from "../../auth";
import {
  fetchMyProfile,
  requestAvatarUploadTarget,
  updateMyAvatarKey,
  updateMyDisplayName,
  updateMyEmail,
  updateMyUsername,
} from "../../api/user";
import EditableFieldCard from "./components/EditableFieldCard";
import { useProfileFieldState } from "./hooks/useProfileFieldState";
import type { ProfileField } from "./hooks/useProfileFieldState";
import { buildS3AssetUrl } from "../../config/s3";

type FormState = {
  username: string;
  email: string;
  displayName: string;
};

const DEFAULT_AVATAR_SRC = "/images/avatars/default-profile.png";

export default function ProfilePage() {
  const { user, isLoading, refresh } = useAuth();
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [form, setForm] = useState<FormState>({ username: "", email: "", displayName: "" });
  const [selectedAvatarFile, setSelectedAvatarFile] = useState<File | null>(null); // local selected file for avatar upload
  const [avatarPreviewSrc, setAvatarPreviewSrc] = useState<string>(DEFAULT_AVATAR_SRC); // local blob preview URL for selected file

  const [isHydrating, setIsHydrating] = useState(false);
  const [loadErrorMessage, setLoadErrorMessage] = useState<string | null>(null);

  const {
    editingByField,
    savingByField,
    errorByField,
    setFieldEditing,
    setFieldSaving,
    setFieldError,
    beginEdit,
    resetAllFieldUiState,
  } = useProfileFieldState();

  useEffect(() => { //deps: [user?.id]. Hydrates profile fields
    if (!user?.id) {
      return;
    }

    let active = true;

    const loadProfile = async () => {
      setIsHydrating(true);
      setLoadErrorMessage(null);

      try {
        const nextProfile = await fetchMyProfile();
        if (!active) {
          return;
        }

        setForm({
          username: nextProfile.username,
          email: nextProfile.email ?? "",
          displayName: nextProfile.displayName ?? "",
        });
        setProfile(nextProfile);
        resetAllFieldUiState();
        setSelectedAvatarFile(null);
        setAvatarPreviewSrc(DEFAULT_AVATAR_SRC);
      } catch (error) {
        if (!active) {
          return;
        }
        setLoadErrorMessage(error instanceof Error ? error.message : "Failed to load profile.");
      } finally {
        if (active) {
          setIsHydrating(false);
        }
      }
    };

    void loadProfile();

    return () => {
      active = false;
    };
  }, [resetAllFieldUiState, user?.id]);

  //when avatarPreviewSrc is changed(e.g. user selects a new image file for avatar), the cleanup function here will clear the blob for the previously selected image.
  useEffect(() => { 
    if (!avatarPreviewSrc.startsWith("blob:")) {
      return;
    }

    return () => {
      URL.revokeObjectURL(avatarPreviewSrc);
    };
  }, [avatarPreviewSrc]);

  //bools that indicate whether a profile value has changed(e.g. used to determine whether or not to show 'save' button for that field)
  const isUsernameDirty = profile ? profile.username !== form.username.trim() : false;
  const isDisplayNameDirty = profile ? (profile.displayName ?? "") !== form.displayName.trim() : false;
  const isEmailDirty = profile ? (profile.email ?? "") !== form.email.trim() : false;
  const isAvatarDirty = selectedAvatarFile !== null;
  const persistedAvatarSrc = buildS3AssetUrl(profile?.avatarKey ?? null);
  const visibleAvatarSrc = selectedAvatarFile ? avatarPreviewSrc : persistedAvatarSrc ?? DEFAULT_AVATAR_SRC;

  // if username is autogenerated(hasn't been set since account creation) then prompt to change it
  const shouldPromptCustomUsername = (profile?.usernameAutoGenerated ?? false) || /^newuser\d*$/i.test(form.username.trim());

  const cancelEdit = (field: ProfileField) => {
    if (!profile) {
      return;
    }

    if (field === "username") {
      setForm((previous) => ({ ...previous, username: profile.username }));
    }

    if (field === "displayName") {
      setForm((previous) => ({ ...previous, displayName: profile.displayName ?? "" }));
    }

    if (field === "email") {
      setForm((previous) => ({ ...previous, email: profile.email ?? "" }));
    }

    if (field === "avatar") {
      setSelectedAvatarFile(null);
      setAvatarPreviewSrc(DEFAULT_AVATAR_SRC);
    }

    setFieldError(field, null);
    setFieldEditing(field, false);
  };

  const handleAvatarFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0] ?? null;
    setSelectedAvatarFile(file);

    if (!file) {
      setAvatarPreviewSrc(DEFAULT_AVATAR_SRC);
      return;
    }

    const localPreviewUrl = URL.createObjectURL(file);
    setAvatarPreviewSrc(localPreviewUrl);
    event.currentTarget.value = "";
  };

  const handleSaveUsername = async () => {
    if (!profile) {
      return;
    }

    if (!isUsernameDirty) {
      setFieldEditing("username", false);
      return;
    }

    try {
      setFieldSaving("username", true);
      setFieldError("username", null);

      const updated = await updateMyUsername(form.username.trim());
      setForm((previous) => ({ ...previous, username: updated.username }));
      setProfile(updated);
      setFieldEditing("username", false);
      await refresh();
    } catch (error) {
      setFieldError("username", error instanceof Error ? error.message : "Failed to save username.");
    } finally {
      setFieldSaving("username", false);
    }
  };

  const handleSaveDisplayName = async () => {
    if (!profile) {
      return;
    }

    if (!isDisplayNameDirty) {
      setFieldEditing("displayName", false);
      return;
    }

    try {
      setFieldSaving("displayName", true);
      setFieldError("displayName", null);

      const trimmedDisplayName = form.displayName.trim();
      const updated = await updateMyDisplayName(trimmedDisplayName ? trimmedDisplayName : null);

      setForm((previous) => ({ ...previous, displayName: updated.displayName ?? "" }));
      setProfile(updated);
      setFieldEditing("displayName", false);
      await refresh();
    } catch (error) {
      setFieldError("displayName", error instanceof Error ? error.message : "Failed to save display name.");
    } finally {
      setFieldSaving("displayName", false);
    }
  };

  const handleSaveEmail = async () => {
    if (!profile) {
      return;
    }

    if (!isEmailDirty) {
      setFieldEditing("email", false);
      return;
    }

    try {
      setFieldSaving("email", true);
      setFieldError("email", null);

      const trimmedEmail = form.email.trim();
      const updated = await updateMyEmail(trimmedEmail ? trimmedEmail : null);

      setForm((previous) => ({ ...previous, email: updated.email ?? "" }));
      setProfile(updated);
      setFieldEditing("email", false);
      await refresh();
    } catch (error) {
      setFieldError("email", error instanceof Error ? error.message : "Failed to save email.");
    } finally {
      setFieldSaving("email", false);
    }
  };

  const handleSaveAvatar = async () => {
    if (!isAvatarDirty) {
      setFieldEditing("avatar", false);
      return;
    }

    try {
      setFieldSaving("avatar", true);
      setFieldError("avatar", null);

      if (!selectedAvatarFile) 
        throw new Error("Must select an avatar file to upload");
      
      
      const payload = {
        mimeType: selectedAvatarFile.type,
        sizeBytes: selectedAvatarFile.size
      };

      const uploadTarget = await requestAvatarUploadTarget(payload);

      const uploadResponse = await fetch(uploadTarget.uploadUrl, {
        method: uploadTarget.method,
        headers: uploadTarget.headers,
        body: selectedAvatarFile,
      });
      if (!uploadResponse.ok) {
        throw new Error(`Avatar upload failed (${uploadResponse.status})`);
      }

      const updated = await updateMyAvatarKey(uploadTarget.objectKey);
      setProfile(updated);
      await refresh();

      setSelectedAvatarFile(null);
      setAvatarPreviewSrc(DEFAULT_AVATAR_SRC);
      setFieldEditing("avatar", false);
    } catch (error) {
      setFieldError("avatar", error instanceof Error ? error.message : "Failed to save profile picture.");
    } finally {
      setFieldSaving("avatar", false);
    }
  };

  if (isLoading) {
    return <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]" />;
  }

  if (user && (isHydrating || !profile)) {
    return <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]" />;
  }

  if (!user) {
    return (
      <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]">
        <div className="mx-auto w-full max-w-3xl rounded-xl border border-[color:var(--line)] bg-[color:var(--panel)]/90 p-5">
          You are not logged in.
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]">
      <div className="mx-auto w-full max-w-3xl rounded-2xl border border-[color:var(--line)] bg-[color:var(--panel)]/90 p-6">
        <h1 className="text-2xl font-semibold tracking-tight">Profile</h1>

        {shouldPromptCustomUsername && (
          <p className="mt-3 rounded-md border border-yellow-500/50 bg-yellow-500/10 px-3 py-2 text-sm text-yellow-300">
            Set a custom user name to personalize your account.
          </p>
        )}

        {!form.displayName.trim() && (
          <p className="mt-3 rounded-md border border-yellow-500/50 bg-yellow-500/10 px-3 py-2 text-sm text-yellow-300">
            Please set a display name soon so friends can recognize you.
          </p>
        )}

        {loadErrorMessage && (
          <p className="mt-3 rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-300">
            {loadErrorMessage}
          </p>
        )}

        <div className="mt-5 grid gap-4">
          <EditableFieldCard
            label="Profile picture"
            isEditing={editingByField.avatar}
            isSaving={savingByField.avatar}
            isDirty={isAvatarDirty}
            onEdit={() => beginEdit("avatar")}
            onSave={() => void handleSaveAvatar()}
            onCancel={() => cancelEdit("avatar")}
            errorMessage={errorByField.avatar}
            contentClassName="mt-3"
          >
            <div className="flex items-center gap-4">
              <img
                src={visibleAvatarSrc}
                alt="Profile picture preview"
                className="h-20 w-20 rounded-full border border-[color:var(--line)] object-cover bg-[color:var(--panel)]"
              />

              <div className="min-w-0 w-full">
                {editingByField.avatar ? (
                  <input
                    type="file"
                    accept="image/png,image/jpeg,image/webp"
                    onChange={handleAvatarFileChange}
                    className="w-full block text-sm text-[color:var(--muted)] file:mr-3 file:rounded-full file:border file:border-[color:var(--line)] file:bg-transparent file:px-3 file:py-1.5 file:text-sm file:text-[color:var(--text)] hover:file:border-[color:var(--text)]"
                  />
                ) : null}

                {editingByField.avatar ? (
                  <p className="mt-1 text-sm text-[color:var(--muted)]">
                    {selectedAvatarFile ? selectedAvatarFile.name : "Choose JPG, PNG, or WEBP"}
                  </p>
                ) : null}
              </div>
            </div>
          </EditableFieldCard>

          <EditableFieldCard
            label="Username"
            isEditing={editingByField.username}
            isSaving={savingByField.username}
            isDirty={isUsernameDirty}
            onEdit={() => beginEdit("username")}
            onSave={() => void handleSaveUsername()}
            onCancel={() => cancelEdit("username")}
            errorMessage={errorByField.username}
          >
            {editingByField.username ? (
              <input
                id="profile-username"
                value={form.username}
                onChange={(event) => setForm((previous) => ({ ...previous, username: event.target.value }))}
                className="w-full rounded-md border border-[color:var(--line)] bg-[color:var(--panel)] px-3 py-2 text-[color:var(--text)] outline-none focus:border-[color:var(--accent)]"
              />
            ) : (
              <p className="text-base font-semibold text-[color:var(--text)]">{form.username}</p>
            )}
          </EditableFieldCard>

          <EditableFieldCard
            label="Display name"
            isEditing={editingByField.displayName}
            isSaving={savingByField.displayName}
            isDirty={isDisplayNameDirty}
            onEdit={() => beginEdit("displayName")}
            onSave={() => void handleSaveDisplayName()}
            onCancel={() => cancelEdit("displayName")}
            errorMessage={errorByField.displayName}
          >
            {editingByField.displayName ? (
              <input
                id="profile-display-name"
                value={form.displayName}
                onChange={(event) => setForm((previous) => ({ ...previous, displayName: event.target.value }))}
                placeholder="Set your display name"
                className="w-full rounded-md border border-[color:var(--line)] bg-[color:var(--panel)] px-3 py-2 text-[color:var(--text)] outline-none focus:border-[color:var(--accent)]"
              />
            ) : (
              <p className="text-base font-semibold text-[color:var(--text)]">
                {form.displayName.trim() || "Not set"}
              </p>
            )}
          </EditableFieldCard>

          <EditableFieldCard
            label="Email (optional)"
            isEditing={editingByField.email}
            isSaving={savingByField.email}
            isDirty={isEmailDirty}
            onEdit={() => beginEdit("email")}
            onSave={() => void handleSaveEmail()}
            onCancel={() => cancelEdit("email")}
            errorMessage={errorByField.email}
          >
            {editingByField.email ? (
              <input
                id="profile-email"
                type="email"
                value={form.email}
                onChange={(event) => setForm((previous) => ({ ...previous, email: event.target.value }))}
                placeholder="Add an email for recovery"
                className="w-full rounded-md border border-[color:var(--line)] bg-[color:var(--panel)] px-3 py-2 text-[color:var(--text)] outline-none focus:border-[color:var(--accent)]"
              />
            ) : (
              <p className="text-base font-semibold text-[color:var(--text)]">{form.email.trim() || "Not set"}</p>
            )}
          </EditableFieldCard>
        </div>
      </div>
    </main>
  );
}
