import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import type { UserProfile } from "@cup/shared-types";
import { useAuth } from "../../auth";
import { fetchMyProfile, updateMyProfile } from "../../api/user";

type FormState = {
  username: string;
  email: string;
  displayName: string;
};

type EditableField = "username" | "displayName" | "email";

export default function ProfilePage() {
  const { user, isLoading, refresh } = useAuth();
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [form, setForm] = useState<FormState>({ username: "", email: "", displayName: "" });
  const [isSaving, setIsSaving] = useState(false);
  const [isHydrating, setIsHydrating] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [editing, setEditing] = useState<Record<EditableField, boolean>>({
    username: false,
    displayName: false,
    email: false,
  });

  useEffect(() => {
    if (!user?.id) {
      return;
    }

    let active = true;

    const loadProfile = async () => {
      setIsHydrating(true);
      setErrorMessage(null);

      try {
        const profile = await fetchMyProfile();
        if (!active) {
          return;
        }

        setForm({
          username: profile.username,
          email: profile.email ?? "",
          displayName: profile.displayName ?? "",
        });
        setProfile(profile);
        setEditing({ username: false, displayName: false, email: false });
      } catch (error) {
        if (!active) {
          return;
        }
        setErrorMessage(error instanceof Error ? error.message : "Failed to load profile.");
      } finally {
        if (active) {
          setIsHydrating(false);
        }
      }
    };

    void loadProfile();

    return () => {
      active = false;
    };
  }, [user?.id]);

  const isDirty = useMemo(() => {
    if (!profile) {
      return false;
    }

    const usernameChanged = profile.username !== form.username.trim();
    const emailChanged = (profile.email ?? "") !== form.email.trim();
    const displayNameChanged = (profile.displayName ?? "") !== form.displayName.trim();
    return usernameChanged || emailChanged || displayNameChanged;
  }, [form.displayName, form.email, form.username, profile]);

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setErrorMessage(null);
    setSuccessMessage(null);

    try {
      setIsSaving(true);
      const updated = await updateMyProfile({
        username: form.username.trim(),
        email: form.email.trim() ? form.email.trim() : null,
        displayName: form.displayName.trim() ? form.displayName.trim() : null,
      });

      setForm({
        username: updated.username,
        email: updated.email ?? "",
        displayName: updated.displayName ?? "",
      });
      setProfile(updated);
      setEditing({ username: false, displayName: false, email: false });

      await refresh();
      setSuccessMessage("Profile saved.");
    } catch (error) {
      setErrorMessage(error instanceof Error ? error.message : "Failed to save profile.");
    } finally {
      setIsSaving(false);
    }
  };

  const beginEdit = (field: EditableField) => {
    setSuccessMessage(null);
    setEditing((prev) => ({ ...prev, [field]: true }));
  };

  const cancelEdit = (field: EditableField) => {
    if (!profile) {
      return;
    }

    if (field === "username") {
      setForm((prev) => ({ ...prev, username: profile.username }));
    }

    if (field === "displayName") {
      setForm((prev) => ({ ...prev, displayName: profile.displayName ?? "" }));
    }

    if (field === "email") {
      setForm((prev) => ({ ...prev, email: profile.email ?? "" }));
    }

    setEditing((prev) => ({ ...prev, [field]: false }));
  };

  const showSaveButton = editing.username || editing.displayName || editing.email;
  const shouldPromptCustomUsername =
    (profile?.usernameAutoGenerated ?? false) || /^newuser\d*$/i.test(form.username.trim());

  if (isLoading) {
    return <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]" />;
  }

  if (user && (isHydrating || !profile)) {
    return <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]" />;
  }

  if (!user) {
    return (
      <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]">
        <div className="mx-auto w-full max-w-3xl rounded-xl border border-[color:var(--line)] bg-[color:var(--panel)]/90 p-5">
          You are not logged in.
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen w-full px-6 pt-24 text-[color:var(--text)]">
      <div className="mx-auto w-full max-w-3xl rounded-2xl border border-[color:var(--line)] bg-[color:var(--panel)]/90 p-6">
        <h1 className="text-2xl font-semibold tracking-tight">Profile</h1>

        {shouldPromptCustomUsername && (
          <p className="mt-3 rounded-md border border-yellow-500/50 bg-yellow-500/10 px-3 py-2 text-sm text-yellow-300">
            Set a custom user name to personalize your account.
          </p>
        )}

        {!form.displayName.trim() && (
          <p className="mt-3 rounded-md border border-yellow-500/50 bg-yellow-500/10 px-3 py-2 text-sm text-yellow-300">
            Please set a display name soon so friends can recognize you.
          </p>
        )}

        {errorMessage && (
          <p className="mt-3 rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-300">
            {errorMessage}
          </p>
        )}

        {successMessage && (
          <p className="mt-3 rounded-md border border-green-500/40 bg-green-500/10 px-3 py-2 text-sm text-green-300">
            {successMessage}
          </p>
        )}

        <form className="mt-5 grid gap-4" onSubmit={handleSubmit}>
          <div className="rounded-md border border-[color:var(--line)] bg-[color:var(--panel-strong)] px-4 py-3">
            <p className="text-xs uppercase tracking-[0.2em] text-[color:var(--muted)]">Username</p>
            <div className="mt-1 flex items-center justify-between gap-3">
              {editing.username ? (
                <input
                  id="profile-username"
                  value={form.username}
                  onChange={(event) => setForm((prev) => ({ ...prev, username: event.target.value }))}
                  className="w-full rounded-md border border-[color:var(--line)] bg-[color:var(--panel)] px-3 py-2 text-[color:var(--text)] outline-none focus:border-[color:var(--accent)]"
                />
              ) : (
                <p className="text-base font-semibold text-[color:var(--text)]">{form.username}</p>
              )}

              {editing.username ? (
                <button
                  type="button"
                  onClick={() => cancelEdit("username")}
                  className="text-xs text-[color:var(--muted)] transition hover:text-[color:var(--text)]"
                >
                  Cancel
                </button>
              ) : (
                <button
                  type="button"
                  onClick={() => beginEdit("username")}
                  className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition hover:border-[color:var(--text)]"
                >
                  Edit
                </button>
              )}
            </div>
          </div>

          <div className="rounded-md border border-[color:var(--line)] bg-[color:var(--panel-strong)] px-4 py-3">
            <div className="flex items-center justify-between gap-3">
              <p className="text-xs uppercase tracking-[0.2em] text-[color:var(--muted)]">Display name</p>
              {editing.displayName ? (
                <button
                  type="button"
                  onClick={() => cancelEdit("displayName")}
                  className="text-xs text-[color:var(--muted)] transition hover:text-[color:var(--text)]"
                >
                  Cancel
                </button>
              ) : (
                <button
                  type="button"
                  onClick={() => beginEdit("displayName")}
                  className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition hover:border-[color:var(--text)]"
                >
                  Edit
                </button>
              )}
            </div>

            {editing.displayName ? (
              <input
                id="profile-display-name"
                value={form.displayName}
                onChange={(event) => setForm((prev) => ({ ...prev, displayName: event.target.value }))}
                placeholder="Set your display name"
                className="mt-2 w-full rounded-md border border-[color:var(--line)] bg-[color:var(--panel)] px-3 py-2 text-[color:var(--text)] outline-none focus:border-[color:var(--accent)]"
              />
            ) : (
              <p className="mt-1 text-base font-semibold text-[color:var(--text)]">
                {form.displayName.trim() || "Not set"}
              </p>
            )}
          </div>

          <div className="rounded-md border border-[color:var(--line)] bg-[color:var(--panel-strong)] px-4 py-3">
            <div className="flex items-center justify-between gap-3">
              <p className="text-xs uppercase tracking-[0.2em] text-[color:var(--muted)]">Email (optional)</p>
              {editing.email ? (
                <button
                  type="button"
                  onClick={() => cancelEdit("email")}
                  className="text-xs text-[color:var(--muted)] transition hover:text-[color:var(--text)]"
                >
                  Cancel
                </button>
              ) : (
                <button
                  type="button"
                  onClick={() => beginEdit("email")}
                  className="rounded-full border border-[color:var(--line)] px-3 py-1 text-xs text-[color:var(--text)] transition hover:border-[color:var(--text)]"
                >
                  Edit
                </button>
              )}
            </div>

            {editing.email ? (
              <input
                id="profile-email"
                type="email"
                value={form.email}
                onChange={(event) => setForm((prev) => ({ ...prev, email: event.target.value }))}
                placeholder="Add an email for recovery"
                className="mt-2 w-full rounded-md border border-[color:var(--line)] bg-[color:var(--panel)] px-3 py-2 text-[color:var(--text)] outline-none focus:border-[color:var(--accent)]"
              />
            ) : (
              <p className="mt-1 text-base font-semibold text-[color:var(--text)]">
                {form.email.trim() || "Not set"}
              </p>
            )}
          </div>

          {showSaveButton && (
            <button
              type="submit"
              disabled={isSaving || isHydrating || !isDirty}
              className="mt-2 w-fit rounded-full border border-[color:var(--line)] px-5 py-2 text-sm text-[color:var(--text)] transition enabled:hover:border-[color:var(--text)] disabled:opacity-60"
            >
              {isSaving ? "Saving..." : "Save changes"}
            </button>
          )}
        </form>
      </div>
    </main>
  );
}
