import { Test, TestingModule } from '@nestjs/testing';
import { UnauthorizedException } from '@nestjs/common';
import { UsersController } from './users.controller';
import { UsersService } from './users.service';
import type { AuthedRequest } from 'src/auth/auth.types';

describe('UsersController', () => {
  let controller: UsersController;
  let usersServiceMock: {
    getMe: jest.Mock;
    updateMe: jest.Mock;
  };

  beforeEach(async () => {
    usersServiceMock = {
      getMe: jest.fn(),
      updateMe: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      controllers: [UsersController],
      providers: [{ provide: UsersService, useValue: usersServiceMock }],
    }).compile();

    controller = module.get<UsersController>(UsersController);
  });

  it('returns current user profile', async () => {
    usersServiceMock.getMe.mockResolvedValue({
      id: 'user-id-123',
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: 'fake@example.com',
      displayName: 'Fake User',
    });

    const req = {
      user: { id: 'user-id-123', username: 'fakeuser', email: 'fake@example.com', displayName: 'Fake User' },
    } as AuthedRequest;

    const result = await controller.me(req);

    expect(usersServiceMock.getMe).toHaveBeenCalledWith('user-id-123');
    expect(result.username).toBe('fakeuser');
  });

  it('throws unauthorized when /users/me requested while logged out', async () => {
    await expect(controller.me({} as AuthedRequest)).rejects.toThrow(UnauthorizedException);
  });

  it('updates current user profile', async () => {
    const req = {
      user: { id: 'user-id-123', username: 'fakeuser', email: null, displayName: null },
    } as AuthedRequest;
    const payload = { displayName: 'Updated Name' };

    usersServiceMock.updateMe.mockResolvedValue({
      id: 'user-id-123',
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: null,
      displayName: 'Updated Name',
    });

    const result = await controller.updateMe(req, payload);

    expect(usersServiceMock.updateMe).toHaveBeenCalledWith('user-id-123', payload);
    expect(result.displayName).toBe('Updated Name');
  });
});
