import { BadRequestException, ConflictException, NotFoundException } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { PrismaService } from 'src/prisma/prisma.service';
import { UsersService } from './users.service';
import { StorageService } from 'src/storage/storage.service';

describe('UsersService', () => {
  let service: UsersService;
  let prismaMock: {
    user: {
      findUnique: jest.Mock;
      update: jest.Mock;
    };
  };
  let storageServiceMock: {
    createAvatarUploadTarget: jest.Mock;
    deleteObject: jest.Mock;
  };

  beforeEach(async () => {
    prismaMock = {
      user: {
        findUnique: jest.fn(),
        update: jest.fn(),
      },
    };

    storageServiceMock = {
      createAvatarUploadTarget: jest.fn(),
      deleteObject: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UsersService,
        {
          provide: PrismaService,
          useValue: prismaMock,
        },
        {
          provide: StorageService,
          useValue: storageServiceMock,
        },
      ],
    }).compile();

    service = module.get<UsersService>(UsersService);
  });

  it('returns profile for existing user', async () => {
    prismaMock.user.findUnique.mockResolvedValue({
      id: 'user-id-123',
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: null,
      displayName: null,
      avatarKey: null,
    });

    const profile = await service.getMe('user-id-123');

    expect(profile.username).toBe('fakeuser');
  });

  it('throws when profile user does not exist', async () => {
    prismaMock.user.findUnique.mockResolvedValue(null);

    await expect(service.getMe('missing-user')).rejects.toThrow(NotFoundException);
  });

  it('updates display name', async () => {
    prismaMock.user.findUnique.mockResolvedValue(null);
    prismaMock.user.update.mockResolvedValue({
      id: 'user-id-123',
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: 'new@example.com',
      displayName: 'New Name',
      avatarKey: null,
    });

    const updated = await service.updateDisplayName('user-id-123', {
      displayName: 'New Name',
    });

    expect(updated.displayName).toBe('New Name');
  });

  it('throws conflict when email already belongs to another account', async () => {
    prismaMock.user.findUnique.mockResolvedValue({ id: 'other-user' });

    await expect(service.updateEmail('user-id-123', { email: 'used@example.com' })).rejects.toThrow(ConflictException);
  });

  it('throws bad request for invalid payload', async () => {
    await expect(service.updateEmail('user-id-123', 'bad-input')).rejects.toThrow(BadRequestException);
  });

  it('updates username and clears auto-generated flag', async () => {
    prismaMock.user.findUnique.mockResolvedValue(null);
    prismaMock.user.update.mockResolvedValue({
      id: 'user-id-123',
      username: 'moe_custom',
      usernameAutoGenerated: false,
      email: null,
      displayName: null,
      avatarKey: null,
    });

    const updated = await service.updateUsername('user-id-123', {
      username: 'moe_custom',
    });

    expect(updated.username).toBe('moe_custom');
  });

  it('rejects avatar uploadTarget requests with a size that is too large', async () => {
    const userId = 'user-id-123';
    const payload = { mimeType: 'image/png', sizeBytes: 5 * 1024 * 1024 };

    await expect(service.requestAvatarUploadTarget(userId, payload)).rejects.toThrow(BadRequestException);
    expect(storageServiceMock.createAvatarUploadTarget).not.toHaveBeenCalled();
  });

  it('returns an avatar uploadTarget for valid requests', async () => {
    const userId = 'user-id-123';
    const payload = { mimeType: 'image/png', sizeBytes: 1 * 1024 * 1024 };

    const mockUploadTarget = {
      uploadUrl: 'https://example-upload-url',
      method: 'PUT' as const,
      headers: { 'Content-Type': 'image/png' },
      objectKey: `dev/avatars/${userId}/test-object.png`,
      expiresInSeconds: 120,
    };

    storageServiceMock.createAvatarUploadTarget.mockResolvedValue(mockUploadTarget);

    const result = await service.requestAvatarUploadTarget(userId, payload);

    expect(result).toEqual(mockUploadTarget);
  });

  it('updates avatarKey successfully', async () => {
    const userId = 'user-id-123';
    const newAvatarKey = `dev/avatars/${userId}/new-avatar.webp`;

    prismaMock.user.findUnique.mockResolvedValueOnce({
      avatarKey: null,
    });

    prismaMock.user.update.mockResolvedValueOnce({
      id: userId,
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: 'fake@example.com',
      displayName: 'Fake User',
      avatarKey: newAvatarKey,
    });
    const result = await service.updateAvatarKey(userId, { avatarKey: newAvatarKey });

    expect(prismaMock.user.update).toHaveBeenCalledWith(
      expect.objectContaining({
        where: { id: userId },
        data: expect.objectContaining({
          avatarKey: newAvatarKey,
        }),
      }),
    );
    expect(result.avatarKey).toBe(newAvatarKey);
  });

  it('rejects when avatarKey is missing', async () => {
    const userId = 'user-id-123';

    await expect(service.updateAvatarKey(userId, {})).rejects.toThrow(BadRequestException);

    expect(prismaMock.user.findUnique).not.toHaveBeenCalled();
    expect(prismaMock.user.update).not.toHaveBeenCalled();
    expect(storageServiceMock.deleteObject).not.toHaveBeenCalled();
  });

  it('rejects invalid avatarKey prefix', async () => {
    const userId = 'user-id-123';
    const invalidKey = `dev/avatars/another-user/sneaky.webp`;

    await expect(service.updateAvatarKey(userId, { avatarKey: invalidKey })).rejects.toThrow(BadRequestException);

    expect(prismaMock.user.findUnique).not.toHaveBeenCalled();
    expect(prismaMock.user.update).not.toHaveBeenCalled();
    expect(storageServiceMock.deleteObject).not.toHaveBeenCalled();
  });

  it('deletes previous avatar object when key changes', async () => {
    const userId = 'user-id-123';
    const oldKey = `dev/avatars/${userId}/old.webp`;
    const newKey = `dev/avatars/${userId}/new.webp`;

    prismaMock.user.findUnique.mockResolvedValueOnce({ avatarKey: oldKey });
    prismaMock.user.update.mockResolvedValueOnce({
      id: userId,
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: null,
      displayName: null,
      avatarKey: newKey,
    });
    const result = await service.updateAvatarKey(userId, { avatarKey: newKey });

    expect(storageServiceMock.deleteObject).toHaveBeenCalledWith(oldKey);
    expect(result.avatarKey).toBe(newKey);
  });

  it('still returns updated profile when old avatar delete fails', async () => {
    const userId = 'user-id-123';
    const oldKey = `dev/avatars/${userId}/old.webp`;
    const newKey = `dev/avatars/${userId}/new.webp`;

    prismaMock.user.findUnique.mockResolvedValueOnce({ avatarKey: oldKey });
    prismaMock.user.update.mockResolvedValueOnce({
      id: userId,
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: null,
      displayName: null,
      avatarKey: newKey,
    });

    const warnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
    storageServiceMock.deleteObject.mockRejectedValueOnce(new Error('S3 delete failed'));

    const result = await service.updateAvatarKey(userId, { avatarKey: newKey });

    expect(result.avatarKey).toBe(newKey);
    expect(storageServiceMock.deleteObject).toHaveBeenCalledWith(oldKey);
    expect(warnSpy).toHaveBeenCalled();
    warnSpy.mockRestore();
  });
});
