import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { AvatarUploadTargetRequest, AvatarUploadTargetResponse, UserProfile } from '@cup/shared-types';
import { PrismaService } from 'src/prisma/prisma.service';
import type { UpdateUserProfileInput } from './users.types';
import { StorageService } from 'src/storage/storage.service';

const MAX_AVATAR_SIZE_BYTES = 2 * 1024 * 1024; // 2MB
const USER_PROFILE_SELECT = {
  id: true,
  username: true,
  usernameAutoGenerated: true,
  email: true,
  displayName: true,
  avatarKey: true,
} as const;

@Injectable()
export class UsersService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly storageService: StorageService,
  ) {}

  async getMe(userId: string): Promise<UserProfile> {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: USER_PROFILE_SELECT,
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    return user;
  }

  // Gets an ObjectKey from s3 to upload avatar image. This is returned to the frontend so that the frontend can directly upload the avatar image to s3
  async requestAvatarUploadTarget(
    userId: string,
    payload: AvatarUploadTargetRequest,
  ): Promise<AvatarUploadTargetResponse> {
    if (!payload || typeof payload !== 'object') throw new BadRequestException('payload must be an object');
    if (typeof payload.mimeType !== 'string') throw new BadRequestException('mimeType must exist and be a string');
    if (typeof payload.sizeBytes !== 'number') throw new BadRequestException('sizeBytes must exist and be a number');
    if (payload.sizeBytes > MAX_AVATAR_SIZE_BYTES)
      throw new BadRequestException(`Avatar must be <= ${MAX_AVATAR_SIZE_BYTES} bytes`);

    return this.storageService.createAvatarUploadTarget(userId, payload.mimeType);
  }

  async updateUsername(userId: string, payload: unknown): Promise<UserProfile> {
    const body = this.parseBody(payload);

    if (!Object.hasOwn(body, 'username')) {
      throw new BadRequestException('username is required');
    }

    const username = this.validateUsername(body.username);
    return this.updateProfile(userId, { username });
  }

  async updateDisplayName(userId: string, payload: unknown): Promise<UserProfile> {
    const body = this.parseBody(payload);

    if (!Object.hasOwn(body, 'displayName')) {
      throw new BadRequestException('displayName is required');
    }

    const displayName = this.validateDisplayName(body.displayName);
    return this.updateProfile(userId, { displayName });
  }

  async updateEmail(userId: string, payload: unknown): Promise<UserProfile> {
    const body = this.parseBody(payload);

    if (!Object.hasOwn(body, 'email')) {
      throw new BadRequestException('email is required');
    }

    const email = this.validateEmail(body.email);
    return this.updateProfile(userId, { email });
  }

  async updateAvatarKey(userId: string, payload: unknown): Promise<UserProfile> {
    const body = this.parseBody(payload);

    if (!Object.hasOwn(body, 'avatarKey')) throw new BadRequestException('avatarKey is required');

    const avatarKey = this.validateAvatarKey(body.avatarKey, userId);

    const existing = await this.prisma.user.findUnique({
      where: { id: userId },
      select: { avatarKey: true },
    });
    if (!existing) throw new NotFoundException('User not found');

    const previousAvatarKey = existing.avatarKey;
    const updated = await this.updateProfile(userId, { avatarKey });

    if (previousAvatarKey && previousAvatarKey !== avatarKey) {
      try {
        await this.storageService.deleteObject(previousAvatarKey);
      } catch (error) {
        console.warn('Failed to delete previous avatar object:', previousAvatarKey, error);
      }
    }

    return updated;
  }

  private async updateProfile(userId: string, updates: UpdateUserProfileInput): Promise<UserProfile> {
    if (updates.username !== undefined) {
      const existing = await this.prisma.user.findUnique({
        where: { username: updates.username },
        select: { id: true },
      });

      if (existing && existing.id !== userId) {
        throw new ConflictException('username is already taken');
      }
    }

    if (updates.email !== undefined && updates.email !== null) {
      const existing = await this.prisma.user.findUnique({
        where: { email: updates.email },
        select: { id: true },
      });

      if (existing && existing.id !== userId) {
        throw new ConflictException('email is already in use');
      }
    }

    const user = await this.prisma.user.update({
      where: { id: userId },
      data: {
        ...(updates.username !== undefined ? { username: updates.username, usernameAutoGenerated: false } : {}),
        ...(updates.displayName !== undefined ? { displayName: updates.displayName } : {}),
        ...(updates.email !== undefined ? { email: updates.email } : {}),
        ...(updates.avatarKey !== undefined ? { avatarKey: updates.avatarKey } : {}),
      },
      select: USER_PROFILE_SELECT,
    });

    return user;
  }

  private parseBody(payload: unknown): Record<string, unknown> {
    if (!payload || typeof payload !== 'object' || Array.isArray(payload)) {
      throw new BadRequestException('Invalid request body');
    }

    return payload as Record<string, unknown>;
  }

  private validateUsername(value: unknown): string {
    if (typeof value !== 'string') {
      throw new BadRequestException('username must be a string');
    }

    const username = value.trim();
    if (!/^[a-zA-Z0-9_]{3,24}$/.test(username)) {
      throw new BadRequestException('username must be 3-24 characters using letters, numbers, or _');
    }

    return username;
  }

  //TODO:: think about whether I want to limit displayName characters
  private validateDisplayName(value: unknown): string | null {
    if (value === null || value === undefined) {
      return null;
    }

    if (typeof value !== 'string') {
      throw new BadRequestException('displayName must be a string');
    }

    const trimmed = value.trim();
    if (!trimmed) {
      return null;
    }

    if (trimmed.length > 50) {
      throw new BadRequestException('displayName must be 50 characters or less');
    }

    return trimmed;
  }

  private validateEmail(value: unknown): string | null {
    if (value === null || value === undefined) {
      return null;
    }

    if (typeof value !== 'string') {
      throw new BadRequestException('email must be a string');
    }

    const email = value.trim().toLowerCase();
    if (!email) {
      return null;
    }

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      throw new BadRequestException('email format is invalid');
    }

    return email;
  }

  private validateAvatarKey(value: unknown, userId: string): string | null {
    if (value === null || value === undefined) {
      return null;
    }
    if (typeof value !== 'string') {
      throw new BadRequestException('avatarKey must be a string');
    }
    const avatarKey = value.trim();
    if (!avatarKey) {
      throw new BadRequestException('avatarKey cannot be empty');
    }
    const envPrefix = process.env.S3_ENV_PREFIX ?? 'dev';
    const requiredPrefix = `${envPrefix}/avatars/${userId}/`;
    if (!avatarKey.startsWith(requiredPrefix)) {
      throw new BadRequestException('avatarKey is not valid for this user');
    }
    return avatarKey;
  }
}
