import { Test, TestingModule } from '@nestjs/testing';
import { UnauthorizedException } from '@nestjs/common';
import { UsersController } from './users.controller';
import { UsersService } from './users.service';
import type { AuthedRequest } from 'src/auth/auth.types';

describe('UsersController', () => {
  let controller: UsersController;
  let usersServiceMock: {
    getMe: jest.Mock;
    updateDisplayName: jest.Mock;
    updateAvatarKey: jest.Mock;
    requestAvatarUploadTarget: jest.Mock;
  };

  beforeEach(async () => {
    usersServiceMock = {
      getMe: jest.fn(),
      updateDisplayName: jest.fn(),
      updateAvatarKey: jest.fn(),
      requestAvatarUploadTarget: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      controllers: [UsersController],
      providers: [{ provide: UsersService, useValue: usersServiceMock }],
    }).compile();

    controller = module.get<UsersController>(UsersController);
  });

  it('returns current user profile', async () => {
    usersServiceMock.getMe.mockResolvedValue({
      id: 'user-id-123',
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: 'fake@example.com',
      displayName: 'Fake User',
    });

    const req = {
      user: { id: 'user-id-123', username: 'fakeuser', email: 'fake@example.com', displayName: 'Fake User' },
    } as AuthedRequest;

    const result = await controller.me(req);

    expect(usersServiceMock.getMe).toHaveBeenCalledWith('user-id-123');
    expect(result.username).toBe('fakeuser');
  });

  it('throws unauthorized when /users/me requested while logged out', async () => {
    await expect(controller.me({} as AuthedRequest)).rejects.toThrow(UnauthorizedException);
  });

  it('updates current user display name', async () => {
    const req = {
      user: { id: 'user-id-123', username: 'fakeuser', email: null, displayName: null },
    } as AuthedRequest;
    const payload = { displayName: 'Updated Name' };

    usersServiceMock.updateDisplayName.mockResolvedValue({
      id: 'user-id-123',
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: null,
      displayName: 'Updated Name',
      avatarKey: null,
    });

    const result = await controller.updateDisplayName(req, payload);

    expect(usersServiceMock.updateDisplayName).toHaveBeenCalledWith('user-id-123', payload);
    expect(result.displayName).toBe('Updated Name');
  });

  describe('avatar routes', () => {
    it('throws unauthorized when avatar upload target is requested while logged out', async () => {
      const payload = {
        mimeType: 'image/png',
        sizeBytes: 1024,
      };

      await expect(controller.requestAvatarUploadTarget({} as AuthedRequest, payload)).rejects.toThrow(
        UnauthorizedException,
      );
    });

    it('requests avatar upload target for authenticated user', async () => {
      const req = {
        user: { id: 'user-id-123', username: 'fakeuser', email: null, displayName: null },
      } as AuthedRequest;
      const payload = {
        mimeType: 'image/png',
        sizeBytes: 1024,
      };

      const serviceResult = {
        uploadUrl: 'https://example-upload-url',
        method: 'PUT' as const,
        headers: { 'Content-Type': 'image/png' },
        objectKey: 'dev/avatars/user-id-123/test.png',
        expiresInSeconds: 120,
      };

      usersServiceMock.requestAvatarUploadTarget.mockResolvedValue(serviceResult);

      const result = await controller.requestAvatarUploadTarget(req, payload);

      expect(usersServiceMock.requestAvatarUploadTarget).toHaveBeenCalledWith('user-id-123', payload);
      expect(result).toEqual(serviceResult);
    });

    it('throws unauthorized when avatar key update is requested while logged out', async () => {
      await expect(
        controller.updateAvatarKey({} as AuthedRequest, { avatarKey: 'dev/avatars/user-id-123/new-avatar.webp' }),
      ).rejects.toThrow(UnauthorizedException);
    });

    it('updates avatar key for authenticated user', async () => {
      const req = {
        user: { id: 'user-id-123', username: 'fakeuser', email: null, displayName: null },
      } as AuthedRequest;
      const payload = {
        avatarKey: 'dev/avatars/user-id-123/new-avatar.webp',
      };

      const serviceResult = {
        id: 'user-id-123',
        username: 'fakeuser',
        usernameAutoGenerated: false,
        email: null,
        displayName: null,
        avatarKey: payload.avatarKey,
      };

      usersServiceMock.updateAvatarKey.mockResolvedValue(serviceResult);

      const result = await controller.updateAvatarKey(req, payload);

      expect(usersServiceMock.updateAvatarKey).toHaveBeenCalledWith('user-id-123', payload);
      expect(result).toEqual(serviceResult);
    });
  });
});
