import { BadRequestException, ConflictException, NotFoundException } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { PrismaService } from 'src/prisma/prisma.service';
import { UsersService } from './users.service';

describe('UsersService', () => {
  let service: UsersService;
  let prismaMock: {
    user: {
      findUnique: jest.Mock;
      update: jest.Mock;
    };
  };

  beforeEach(async () => {
    prismaMock = {
      user: {
        findUnique: jest.fn(),
        update: jest.fn(),
      },
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UsersService,
        {
          provide: PrismaService,
          useValue: prismaMock,
        },
      ],
    }).compile();

    service = module.get<UsersService>(UsersService);
  });

  it('returns profile for existing user', async () => {
    prismaMock.user.findUnique.mockResolvedValue({
      id: 'user-id-123',
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: null,
      displayName: null,
    });

    const profile = await service.getMe('user-id-123');

    expect(profile.username).toBe('fakeuser');
  });

  it('throws when profile user does not exist', async () => {
    prismaMock.user.findUnique.mockResolvedValue(null);

    await expect(service.getMe('missing-user')).rejects.toThrow(NotFoundException);
  });

  it('updates display name and email', async () => {
    prismaMock.user.findUnique.mockResolvedValue(null);
    prismaMock.user.update.mockResolvedValue({
      id: 'user-id-123',
      username: 'fakeuser',
      usernameAutoGenerated: false,
      email: 'new@example.com',
      displayName: 'New Name',
    });

    const updated = await service.updateMe('user-id-123', {
      email: 'new@example.com',
      displayName: 'New Name',
    });

    expect(updated.email).toBe('new@example.com');
    expect(updated.displayName).toBe('New Name');
  });

  it('throws conflict when email already belongs to another account', async () => {
    prismaMock.user.findUnique.mockResolvedValue({ id: 'other-user' });

    await expect(service.updateMe('user-id-123', { email: 'used@example.com' })).rejects.toThrow(ConflictException);
  });

  it('throws bad request for invalid payload', async () => {
    await expect(service.updateMe('user-id-123', 'bad-input')).rejects.toThrow(BadRequestException);
  });

  it('updates username and clears auto-generated flag', async () => {
    prismaMock.user.findUnique.mockResolvedValue(null);
    prismaMock.user.update.mockResolvedValue({
      id: 'user-id-123',
      username: 'moe_custom',
      usernameAutoGenerated: false,
      email: null,
      displayName: null,
    });

    const updated = await service.updateMe('user-id-123', {
      username: 'moe_custom',
    });

    expect(updated.username).toBe('moe_custom');
  });
});
