export type SessionUser = {
  id: string;
  username: string;
  email: string | null;
  displayName: string | null;
};

export type UserProfile = {
  id: string;
  username: string;
  usernameAutoGenerated: boolean;
  email: string | null;
  displayName: string | null;
};
